"""extend track model

Revision ID: 02118f4ae19e
Revises: 0eb6526024d1
Create Date: 2026-07-01 13:25:21.917427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02118f4ae19e'
down_revision: Union[str, Sequence[str], None] = '0eb6526024d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('popularity', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('explicit', sa.Boolean(), nullable=True))
    op.add_column('tracks', sa.Column('preview_url', sa.String(length=500), nullable=True))
    op.add_column('tracks', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('tracks', sa.Column('release_date', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'release_date')
    op.drop_column('tracks', 'image_url')
    op.drop_column('tracks', 'preview_url')
    op.drop_column('tracks', 'explicit')
    op.drop_column('tracks', 'popularity')
    op.drop_column('tracks', 'duration_ms')
    # ### end Alembic commands ###
