"""add track audio features

Revision ID: 1149d47785fa
Revises: cd2abf845695
Create Date: 2026-07-01 21:20:43.693203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1149d47785fa'
down_revision: Union[str, Sequence[str], None] = 'cd2abf845695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('bpm', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('musical_key', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('mode', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('energy', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('danceability', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('valence', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('loudness', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('acousticness', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('instrumentalness', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('speechiness', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('liveness', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('camelot_key', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'camelot_key')
    op.drop_column('tracks', 'liveness')
    op.drop_column('tracks', 'speechiness')
    op.drop_column('tracks', 'instrumentalness')
    op.drop_column('tracks', 'acousticness')
    op.drop_column('tracks', 'loudness')
    op.drop_column('tracks', 'valence')
    op.drop_column('tracks', 'danceability')
    op.drop_column('tracks', 'energy')
    op.drop_column('tracks', 'mode')
    op.drop_column('tracks', 'musical_key')
    op.drop_column('tracks', 'bpm')
    # ### end Alembic commands ###
