"""create audio files table

Revision ID: bdf757401943
Revises: 232e74aaed11
Create Date: 2026-07-06 00:37:25.179336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf757401943'
down_revision: Union[str, Sequence[str], None] = '232e74aaed11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_path'), 'audio_files', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_files_path'), table_name='audio_files')
    op.drop_table('audio_files')
    # ### end Alembic commands ###
