"""add track timing models

Revision ID: c60ac704cc71
Revises: bdf757401943
Create Date: 2026-07-08 18:30:29.837190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60ac704cc71'
down_revision: Union[str, Sequence[str], None] = 'bdf757401943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_beats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('beat_index', sa.Integer(), nullable=False),
    sa.Column('time_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_beats_track_id'), 'track_beats', ['track_id'], unique=False)
    op.create_table('track_cues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('cue_type', sa.String(length=50), nullable=False),
    sa.Column('time_seconds', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_cues_track_id'), 'track_cues', ['track_id'], unique=False)
    op.create_table('track_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_structures_track_id'), 'track_structures', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_structures_track_id'), table_name='track_structures')
    op.drop_table('track_structures')
    op.drop_index(op.f('ix_track_cues_track_id'), table_name='track_cues')
    op.drop_table('track_cues')
    op.drop_index(op.f('ix_track_beats_track_id'), table_name='track_beats')
    op.drop_table('track_beats')
    # ### end Alembic commands ###
